name: Test

on: [push, pull_request]

jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Install native dependencies"
        run: sudo apt-get install libacl1-dev libfuse3-dev pkg-config

      - name: "Install stable toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # If you update this, update the Cargo.toml as well.
          toolchain: "1.63.0"
          override: true

      - name: "Run cargo check"
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Install native dependencies"
        run: sudo apt-get install libacl1-dev libfuse3-dev pkg-config acl fuse3

      - name: "Install stable toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # If you update this, update the Cargo.toml as well.
          toolchain: "1.63.0"
          override: true

      - name: "Run cargo test"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features 'encryption compression file-metadata hash-algorithms repo-version repo-value repo-file repo-content'

  lints:
    name: "Lints"
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Install native dependencies"
        run: sudo apt-get install libacl1-dev libfuse3-dev pkg-config

      - name: "Install stable toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: "Run cargo fmt"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: "Run cargo clippy"
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features

  docs:
    name: "Docs"
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings --cfg docsrs"
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Install rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: "Run cargo doc"
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: doc
          args: "--all-features --no-deps"
